# Generated by Django 4.1.1 on 2022-10-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='DEFAULT VALUE', max_length=1000)),
                ('img', models.FileField(upload_to='')),
                ('web', models.CharField(default='DEFAULT VALUE', max_length=700)),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_up', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
    ]
